FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

RUN ./mvnw dependency:go-offline

COPY src src

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]